version: '3.7'

services:
  app:
    build: .
    command: "/app/server"
    environment:
      - http_client_timeouts_in_seconds=2
      - aggregate_repeat_timeouts_in_seconds=10
      - services_urls=http://sensor1:8080;http://sensor2:8080;http://sensor3:8080;http://sensor4:8080
      - address=:8080
    ports:
      - 8080:8080
  sensor1:
    image: youla_dev_internship_task_go_sensor:latest
    container_name: sensor1
    ports:
      - "8081:8080"
  sensor2:
    image: youla_dev_internship_task_go_sensor:latest
    container_name: sensor2
    ports:
      - "8082:8080"
  sensor3:
    image: youla_dev_internship_task_go_sensor:latest
    container_name: sensor3
    ports:
      - "8083:8080"
  sensor4:
    image: youla_dev_internship_task_go_sensor:latest
    container_name: sensor4
    ports:
      - "8084:8080"
